### ISSUE TITLE
[IDTA-02002-1-0 Contact Information] semanticId in template files for SMC "IPCommunication" does not match specification

### ISSUE THREAD

**Issue by rjI3E7** [admin-shell-io/submodel-templates#188]
In the template JSON file [`IDTA 02002-1-0_Template_ContactInformation.json`](https://github.com/admin-shell-io/submodel-templates/blob/main/published/Contact%20Information/1/IDTA%2002002-1-0_Template_ContactInformation.json) as well as the template [`AASX File`](https://github.com/admin-shell-io/submodel-templates/blob/main/published/Contact%20Information/1/IDTA%2002002-1-0_Template_ContactInformation.aasx) the semanticId for SMC does not match the value of the specification.

According to the specification ([Page 17](https://github.com/admin-shell-io/submodel-templates/blob/main/published/Contact%20Information/1/IDTA%2002002-1-0_Submodel_ContactInformation.pdf)) the value is supposed to be
`https://admin-shell.io/zvei/nameplate/1/0/ContactInformations/ContactInformation/IPCommunication/`

However the last part of the path is missing in the template files.
JSON:
https://github.com/admin-shell-io/submodel-templates/blob/main/published/Contact%20Information/1/IDTA%2002002-1-0_Template_ContactInformation.json#L594

AASX:
<img width="1511" height="928" alt="Image" src="https://github.com/user-attachments/assets/154019f0-7ad1-499c-9270-b9110492e848" />

**Comment by Rudra-sandeep** [comment]
@rjI3E7 Thank you for raising the issue. The issue has been resolved please refer to the latest bug fix version release of the submodel template.

Note: Closing the issue. Feel free to reopen if needed.

**Comment by rjI3E7** [comment]
@Rudra-sandeep Thank you for the heads up.

However the semanticId is still missing the SMC Part for Contact Information. As stated in the specification:
https://admin-shell.io/zvei/nameplate/1/0/ContactInformations/ContactInformation/IPCommunication/

The updated value in https://github.com/admin-shell-io/submodel-templates/blame/4b379d0196f7659df4d0bbb42bd97a5d1534fd92/published/Contact%20Information/1/0/1/IDTA%2002002-1-0-1_Template_ContactInformation.json#L606 is now still missing the **ContactInformation/** part
```json [1-12]
            {
              "idShort": "IPCommunication__00__",
              "semanticId": {
                "type": "ExternalReference",
                "keys": [
                  {
                    "type": "GlobalReference",
                    "value": "https://admin-shell.io/zvei/nameplate/1/0/ContactInformations/IPCommunication/"
                  }
                ]
              },
            }
```
Hope this helps
I do not have access to reopening to issue.
